services:
  imd-automation:
    build:
      context: .
    container_name: imd-automation
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./Download:/app/Download
    command: /entrypoint.sh
  django:
      container_name: django
      build:
        context: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app
      ports:
        - "8006:8000"
      env_file:
        - .env