# Generated by Django 6.0.3 on 2026-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imd_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cluster', models.CharField(max_length=50)),
                ('maximum_past_24hrs', models.FloatField(blank=True, null=True)),
                ('minimum_past_24hrs', models.FloatField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imd_cluster_temperature',
                'unique_together': {('date', 'cluster')},
            },
        ),
    ]
